### ISSUE TITLE
Cannot export HTML+JSON

### ISSUE THREAD

**Issue by jeanmich82** [clipperz/password-manager#100]
Export to HTML+JSON format doesn't work when there is a lot of cards, it freezes on "exporting" message.
If you need more details I can help.

**Comment by jerefeltan** [comment]
It's working for me. Tested in Windows 10, Chrome 48 and Firefox 44, Release 2015.12.16 ( `19290fd` ).

**Comment by jeanmich82** [comment]
Yes it works with few cards, but I have an account with 160 cards and it doesn't work with this account.

**Comment by mbarulli** [comment]
I've 300+ cards and it works nicely.
Do you get any specific error on the JS console?

**Comment by jeanmich82** [comment]
Here is the log error.

`ERROR [DirectLogin.updateBindingsAfterChangingBookmarkletConfiguration] Object { message: "Clipperz.Base.exception.MandatoryPa…", name: "Clipperz.Base.exception.MandatoryPa…", stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [this._bindings is defined <else>] Object { message: "Clipperz.Base.exception.MandatoryPa…", name: "Clipperz.Base.exception.MandatoryPa…", stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [DirectLogin.bindings] Object { message: "Clipperz.Base.exception.MandatoryPa…", name: "Clipperz.Base.exception.MandatoryPa…", stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [DirectLogin.serializedData] Object { message: Object, stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [Record.exportDirectLogins] Object { message: Object, stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [Record.export] Object { message: Object, stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [ExportController.run__exportRecord] Object { message: Object, stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [ExportController.run] Object { message: Object, stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539
ERROR [MainController.downloadExport_handler] Object { message: Object, stack: "MochiKit.Base.__new__@https://clipp…" } app:2441:539`

**Comment by gusarov** [comment]
same here.... lots of:
Clipperz.Crypto.Base.exception.CorruptedMessage
I know I have at least 1 corrupted card (unfortunately very expensive one...)

**Comment by gcsolaroli** [comment]
Hello Dmitry,

are you having this issue using the online version of the application, or are you using your own instance of the "Community Edition"?

Unfortunately, there is not much you can do to restore a corrupted encrypted data. :(
The most I could try to do (and I actually did it in a previous version of the application -gamma- and I am still not sure why it is not working on the new version -delta) is to skip the corrupted card during export, so that you can at least get all your readable data back.

Please copy here a full list of the logs from the Javascript console, from the when you click the export button, until it stops with the error.

Sorry again for the trouble.

Cheers,

Giulio Cesare

**Comment by gusarov** [comment]
Hello, yep, I'm using online version (clipperz.com)

Here is the logs (I've cleared console before clicking 'export')

ERROR [User.recordWithData] TypeError: Cannot read property 'setRemoteData'
of undefined
    at (index):1877
    at Clipperz.Async.Deferred._fire ((index):2023)
    at Clipperz.Async.Deferred._resback ((index):2008)
    at cb ((index):2023)
    at Clipperz.Async.Deferred._fire ((index):2023)
    at Clipperz.Async.Deferred.addCallbacks ((index):2017)
    at Clipperz.Async.Deferred.addBoth ((index):2013)
    at Clipperz.Async.Deferred._fire ((index):2026)
    at Clipperz.Async.Deferred._resback ((index):2008)
    at cb ((index):2023)
VM33:1 XHR finished loading: POST "https://clipperz.is/json".
(anonymous) @ VM33:1
sendXMLHttpRequest @ (index):2031
_doXHR @ (index):6730
newfunc @ (index):1888
(anonymous) @ (index):2042
_fire @ (index):2023
_resback @ (index):2008
callback @ (index):2010
newfunc @ (index):1888
setTimeout (async)
wait @ (index):2042
callLater @ (index):2042
doXHR @ (index):6721
newfunc @ (index):1888
_fire @ (index):2023
_resback @ (index):2008
callback @ (index):2010
callback @ (index):6702
_sendMessage @ (index):7377
newfunc @ (index):1888
_fire @ (index):2023
_resback @ (index):2008
callback @ (index):2010
callback @ (index):6702
sendMessage @ (index):7371
(anonymous) @ (index):7371
newfunc @ (index):1888
_fire @ (index):2023
_resback @ (index):2008
cb @ (index):2023
_fire @ (index):2023
addCallbacks @ (index):2017
addBoth @ (index):2013
_fire @ (index):2026
_resback @ (index):2008
callback @ (index):2010
callback @ (index):6702
processMessage @ (index):7371
message @ (index):7371
newfunc @ (index):1888
_fire @ (index):2023
_resback @ (index):2008
callback @ (index):2010
callback @ (index):6702
sendMessage @ (index):7471
message @ (index):7470
newfunc @ (index):1888
_fire @ (index):2023
_resback @ (index):2008
callback @ (index):2010
callback @ (index):6702
callbacks @ (index):6712
getRecordsLoadingAllData @ (index):7534
newfunc @ (index):1888
_fire @ (index):2023
_resback @ (index):2008
callback @ (index):2010
callback @ (index):6702
downloadExport_handler @ (index):7810
newfunc @ (index):1888
_fire @ (index):2023
_resback @ (index):2008
callback @ (index):2010
callback @ (index):6702
eventHandlerErrorCatcher @ (index):7776
newfunc @ (index):1888
signal @ (index):2250
handleExportLink @ (index):7712
r @ (index):2289
i @ (index):2289
u @ (index):2289
p @ (index):2289
f @ (index):2289
r @ (index):2289
processEventQueue @ (index):2289
r @ (index):2289
handleTopLevel @ (index):2289
i @ (index):2289
a @ (index):2289
perform @ (index):2289
batchedUpdates @ (index):2289
a @ (index):2289
dispatchEvent @ (index):2289
(index):6745 Error while decrypting data [3]
(index):6745 ERROR [Crypto[0.3].deferredDecrypt] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getDecryptedData <inner
deferred>] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [KeyValueObjectStore.deferredGetOrSet [decryptedData]]
m.NamedError {message: "Clipperz.Crypto.Base.exception.CorruptedMessage",
name: "Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getDecryptedData] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject._getObjectDataStore <inner
deferred>] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject._getObjectDataStore] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getValue] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [Record.versions] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [Record.getVersionKey] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [KeyValueObjectStore.deferredGetOrSet [decryptionKey]]
m.NamedError {message: "Clipperz.Crypto.Base.exception.CorruptedMessage",
name: "Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getKey] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [Record.export] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [ExportController.run__exportRecord] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 Error while decrypting data [3]
(index):6745 ERROR [Crypto[0.3].deferredDecrypt] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getDecryptedData <inner
deferred>] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [KeyValueObjectStore.deferredGetOrSet [decryptedData]]
m.NamedError {message: "Clipperz.Crypto.Base.exception.CorruptedMessage",
name: "Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getDecryptedData] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject._getObjectDataStore <inner
deferred>] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject._getObjectDataStore] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getValue] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 Error while decrypting data [3]
(index):6745 ERROR [Crypto[0.3].deferredDecrypt] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getDecryptedData <inner
deferred>] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [KeyValueObjectStore.deferredGetOrSet [decryptedData]]
m.NamedError {message: "Clipperz.Crypto.Base.exception.CorruptedMessage",
name: "Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getDecryptedData] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject._getObjectDataStore <inner
deferred>] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject._getObjectDataStore] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [EncryptedRemoteObject.getValue] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [DirectLogin.setValue] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR
[DirectLogin.updateBindingsAfterChangingBookmarkletConfiguration]
m.NamedError {message: "Clipperz.Crypto.Base.exception.CorruptedMessage",
name: "Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [this._bindings is defined <else>] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [DirectLogin.bindings] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [DirectLogin.serializedData] {message: {…}}
(index):6745 ERROR [Record.exportDirectLogins] {message: {…}}
(index):6745 ERROR [Record.export] {message: {…}}
(index):6745 ERROR [ExportController.run__exportRecord] {message: {…}}
(index):6745 ERROR [ExportController.run] m.NamedError {message:
"Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [MainController.downloadExport_handler] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}
(index):6745 ERROR [MainController.eventHandlerErrorCatcher] m.NamedError
{message: "Clipperz.Crypto.Base.exception.CorruptedMessage", name:
"Clipperz.Crypto.Base.exception.CorruptedMessage"}

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
