### ISSUE TITLE
Bookmarklet unable to collect login configuration

### ISSUE THREAD

**Issue by mbarulli** [clipperz/password-manager#11]
There are websites where the Clipperz bookmarklet is unable to collect information about the login form.
Here are some examples:
- [myspace.com](http://www.myspace.com)
  user cannot select the "copy configuration" button, dimmed underneath the lightbox containing the login form 
- [lufthansa.com](http://www.lufthansa.com)
  the bookmarklet does not recognize the presence of the login form on the page

Thanks,
Marco

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
