### ISSUE TITLE
Failed register

### ISSUE THREAD

**Issue by Rachxunil** [clipperz/password-manager#110]
Hi,
I'm testing this solution and I'mhaving some registration troubles :

**<-- Here the screenshot -->**

![failed](https://cloud.githubusercontent.com/assets/20761117/20064112/d755b4b4-a509-11e6-9f15-6e43d2f46539.png)

**Here some logs : (error.log)**

``
[Wed Nov 02 16:57:49.361404 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] registration, referer: http://xxx.xxx.xxx.xxx
[Wed Nov 02 16:57:49.363113 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] result: {"result":{"lock":"","result":"done"}}, referer: http://xxx.xxx.xxx.xxx
[Wed Nov 02 16:57:49.392571 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] handshake, referer: http://xxx.xxx.xxx.xxx
[Wed Nov 02 16:57:49.648845 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] result: {"result":{"s":"112233445566778899aabbccddeeff00112233445566778899aabbccddeeff00","B":"40ad5382cf88d52b324a91c2ffe03f549e1b333b5525ec9f1bc3a4ba589fd00a"}}, referer: http://172.30.1.169/
[Wed Nov 02 16:57:49.751762 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] handshake, referer: http://xxx.xxx.xxx.xxx
[Wed Nov 02 16:57:49.752091 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] credentialCheck, referer: http://xxx.xxx.xxx.xxx
[Wed Nov 02 16:57:49.806942 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] result: {"result":{"error":"?"}}, referer: 
[Wed Nov 02 16:57:49.849723 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] handshake, referer: 
[Wed Nov 02 16:57:50.103948 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] result: {"result":{"s":"112233445566778899aabbccddeeff00112233445566778899aabbccddeeff00","B":"4bc31f97d38e53bddf0121f41a3c2acb771f2092e131a8e85533905e7d102299"}}, referer: http://172.30.1.169/
[Wed Nov 02 16:57:50.178522 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] handshake, referer: http://xxx.xxx.xxx.xxx
[Wed Nov 02 16:57:50.178848 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] credentialCheck, referer: http://xxx.xxx.xxx.xxx
[Wed Nov 02 16:57:50.232717 2016] [:error] [pid 12680] [client http://xxx.xxx.xxx.xxx] result: {"result":{"error":"?"}}, referer: http://xxx.xxx.xxx.xxx
``

Cordially,
Loowkis

**Comment by Negossia** [comment]
I have the same error

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
