### ISSUE TITLE
Clone is broken on flask backend (maybe on others too)

### ISSUE THREAD

**Issue by misuzu** [clipperz/password-manager#111]
1. setup flask backend with clean postgres database
2. create account
3. clone email sample and fill with random data
4. logout & login
5. check cloned sample

expected behavior:
cloned email sample with random data is displayed

actual behavior:
Wait animation and "Error while decrypting data" in console.

**Comment by misuzu** [comment]
@jokajak yes. Had to fix this in code by hand.

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
