### ISSUE TITLE
On lastest stable Chromium  and Firefox browsers the app failes to start

### ISSUE THREAD

**Issue by azazel75** [clipperz/password-manager#119]
Hello, 

I tried today to login into my clipperz account, the login procedure is succesful but then the startup procedure never completes.  Opening the dev console gives me the following error:

> Uncaught TypeError: Cannot read property 'status' of null
>     at t.renderCertificateInfo ((index):7238)
>     at newfunc ((index):1446)
>     at Object.map ((index):1422)
>     at t.render ((index):7239)
>     at c._renderValidatedComponentWithoutOwnerOrContext ((index):1847)
>     at c._renderValidatedComponent ((index):1847)
>     at c._updateRenderedComponent ((index):1847)
>     at c._performComponentUpdate ((index):1847)
>     at c.updateComponent ((index):1847)
>     at c.receiveComponent ((index):1847)

I'm using chromium version: Version 56.0.2924.76 built on Debian 9.0, running on Debian 9.0 (64-bit)

**Comment by gcsolaroli** [comment]
Hello @azazel75, please double check that your are loading the latest version of the application: f8a0ea7f62402ffa2a79235012adcb77f085b0d4

**Comment by azazel75** [comment]
>>>>> "Giulio" == Giulio Cesare Solaroli <notifications@github.com> writes:

    Giulio> Hello @azazel75, please double check that your are loading the latest version of the application: f8a0ea7f62402ffa2a79235012adcb77f085b0d4

clearing the browser cache did the right thing and now it's
working. Sorry for the noise.

Alberto

**Comment by gcsolaroli** [comment]
No problem.
