### ISSUE TITLE
Clipperz.PM.DataModel.User.exception.LoginFailed while register user

### ISSUE THREAD

**Issue by Git-Rajkumar** [clipperz/password-manager#121]
I have follow this [document](https://vwiki.co.uk/Clipperz_Password_Manager)  to setup clipperz in ubuntu14.04. 

After, I have open clipperz home page , next I have register new account, but  its throw this error **Clipperz.PM.DataModel.User.exception.LoginFailed**

I have check my database **user table**, its saved user details.  But When I login its throw  Login Failed error.

Suggest em How can fix this issue. or suggest me any others better link to setup this.

**Comment by meoso** [comment]
as far as i can tell this project is in it's death throws.  reference https://github.com/clipperz/password-manager/issues/69

You can git clone aunxx's http://git.whoc.org.uk/git/password-manager.git with better results, but i did it on newer Ubuntu 16.04

**Comment by tusharjambhekar** [comment]
Hi. the http://git.whoc.org.uk/git/password-manager.git is not available now.
Where can I find the stable branch of Clipperz.
I am also facing same issue on Centos 7.

Please reply me.

thanks,

**Comment by meoso** [comment]
yes it is, you can only git clone it, not browse via http.
try `git clone --depth 1 http://git.whoc.org.uk/git/password-manager.git`

**Comment by tusharjambhekar** [comment]
Hi,
I have installed clipperz with git clone --depth 1 http://git.whoc.org.uk/git/password-manager.git on CentOS Linux 7 and I am accessing http://hostname/target/php/delta/index.html but then when I register new user can able to see in DB but unable to login with that user.
What to do about this.
Kindly assist me to resolve this.


Thanks,

**Comment by tusharjambhekar** [comment]
Hi, I am still unable to sign up for the new registered user id.I am able to see entry is there at DB.


Thanks,

**Comment by tusharjambhekar** [comment]
Clipperz.PM.DataModel.User.exception.L
![image](https://user-images.githubusercontent.com/25099285/34383028-a89bf298-eb38-11e7-8283-01485fbe1e93.png)

I am using Ubuntu 16.04.3 LTS I have followed the : https://vwiki.co.uk/Clipperz_Password_Manager
then also I am getting following errors in apache2/error.log
[Wed Dec 27 05:32:37.298254 2017] [:error] [pid 18611] [client 172.31.25.11:58198] registration, referer: https://172.31.26.6/clipperz//beta/index.html
[Wed Dec 27 05:32:37.301354 2017] [:error] [pid 18611] [client 172.31.25.11:58198] result: {"result":{"lock":"new lock","result":"done"}}, referer: https://172.31.26.6/clipperz//beta/index.html
[Wed Dec 27 05:32:38.334327 2017] [:error] [pid 18611] [client 172.31.25.11:58198] handshake, referer: https://172.31.26.6/clipperz//beta/index.html
[Wed Dec 27 05:32:38.334620 2017] [:error] [pid 18611] [client 172.31.25.11:58198] PHP Fatal error:  Uncaught Error: Call to undefined function bcscale() in /var/www/html/clipperz/index.php:69\nStack trace:\n#0 /var/www/html/clipperz/index.php(254): base2dec('115b8b692e0e045...', 16)\n#1 {main}\n  thrown in /var/www/html/clipperz/index.php on line 69, referer: https://172.31.26.6/clipperz//beta/index.html
[Wed Dec 27 05:32:38.390559 2017] [:error] [pid 19121] [client 172.31.25.11:58200] handshake, referer: https://172.31.26.6/clipperz//beta/index.html
[Wed Dec 27 05:32:38.390830 2017] [:error] [pid 19121] [client 172.31.25.11:58200] PHP Fatal error:  Uncaught Error: Call to undefined function bcscale() in /var/www/html/clipperz/index.php:69\nStack trace:\n#0 /var/www/html/clipperz/index.php(254): base2dec('115b8b692e0e045...', 16)\n#1 {main}\n  thrown in /var/www/html/clipperz/index.php on line 69, referer: https://172.31.26.6/clipperz//beta/index.html

Kindly let me know how can I troubleshoot this?

**Comment by jokajak** [comment]
Undefined bcscale means you need to install the php extension bcmath

**Comment by tusharjambhekar** [comment]
Hello,
Thank you very much for the reply.I can able to login clipperz.

Thanks,

**Comment by gcsolaroli** [comment]
Thanks @jokajak for the helping out @tusharjambhekar.

**Comment by njdro** [comment]
sorry to necro-bump -- anyone still looking at this OLD issue trying to locate @aunxx's fork, it is 
- https://github.com/aunxx/password-manager

**Comment by aunxx** [comment]
Hi.

Yes, that's the repo with the latest version. tag 1.2.0 I believe is the last, and the one I still use. 

Let me know if you've any issues. I've not looked at the code for a while, but hopefully should still be working.
