### ISSUE TITLE
Tell to allow cookies when login fails because they're blocked

### ISSUE THREAD

**Issue by th00mask** [clipperz/password-manager#122]
I tried to log in from my phone, with Firefox on which I blocked the cookies. The login kept failing and I believed that I made some typo in the password, but after retyping it a dozen times I finally realized that it might be because my browser was blocking cookies. I allowed them and I finally was able to log in.

Woukd be great if the error message told us to allow cookies for the website instead of just showing an uninformative "failed". It would have avoided me to type my password 15 times before realizing that the problem was coming from elsewhere... 😅

**Comment by gcsolaroli** [comment]
New `/epsilon` version will no longer use cookies, not even the session one currently used by `/delta`.
