### ISSUE TITLE
Integrate haveibeenpwned

### ISSUE THREAD

**Issue by daniel-sc** [clipperz/password-manager#134]
Clipperz should be able to indicate breached passwords using https://haveibeenpwned.com

Similar to: https://blog.1password.com/finding-pwned-passwords-with-1password/

**Comment by qoomon** [comment]
WDYT?

**Comment by cariaso** [comment]
-1
Do one thing, and do it well.

**Comment by qoomon** [comment]
Any news on that topic, I think it would be a really nice feature to be able to check all your password (hidden fields) against HIBP once in a while. Currently I need to export clipperz and then run my [own script](https://gist.magentonotes.com/qoomon/17ac72a2c90bb85b89c883ce7dac5724) on it, that is quite unhandy.

**Comment by gcsolaroli** [comment]
We are not really eager on integrating directly from Clipperz to other site.
We long ago also removed loading `favicon` images, in order to avoid sending `referrer` information (containing Clipperz url) to random sites.
