### ISSUE TITLE
Clipperz next generation with kotlin

### ISSUE THREAD

**Issue by qoomon** [clipperz/password-manager#135]
Maybe it is worth looking at kotlin instead of purescript as the new strongly typed main language as well, because kotlin code can be compiled to js too.

**Comment by gcsolaroli** [comment]
Unfortunately, I am personally much more interested in learning Haskell/PureScript, than Kotlin. 😁

It may be a harder path to begin with, but it is way more compelling for me.

PureScript is also been used for web development in the [Cardano project][cardano], that is one of the most interesting crypto projects, expecially with regards to code development practices.

[cardano]:https://help.cardano.org/english/why-cardano/why-haskell

**Comment by qoomon** [comment]
ah I see, just wanted to mention kotlin :-D
BTW thx a lot for this great pw manager
