### ISSUE TITLE
clipperz and php 7

### ISSUE THREAD

**Issue by LeoBolien** [clipperz/password-manager#137]
Hello,
has someone migrated clipperz to run with php 7 ?

Thanks and regards
Leo

**Comment by aunxx** [comment]
Hi Leo,
Have a look at this thread:
https://github.com/clipperz/password-manager/issues/69

I've a repo which I use which works with PHP 7, and the details are in that thread.

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
