### ISSUE TITLE
Card does not load, prevents unencrypted HTML+JSON export

### ISSUE THREAD

**Issue by mt-mrx** [clipperz/password-manager#139]
Hi,

since June 2020 I'm using the php7 version of clipperz(delta) from aunxx. After setup troubles (caused by myself) it's working fine since then.

Today I stumbled across exactly one card in my list (I have 512 active and 76 archived) which does not load when clicking it. I just get the rotating progress indicator on the right hand side.
I checked all other cards one by one and they all load correctly.
I can download an offline copy and that works fine except for the same one card.
I tried exporting as unecrypted HTML+JSON, it starts, I see the rotating progress indicator and the progress bar fills as well, but when ich reaches the right hand side it never completes. Same happens in the offline copy.
I'm assuming that one card is the reason for it.

To me it looks like that card was somehow(maybe accessed from two different browsers/devices) corrupted.

Is there any way to fix it?

I looked into the database and have figured out which my userid(51) is, since I have only 3 users in total.
In my last working offline copy from 2020-06-17, the problematic card (and the export) still works. I modified the card since then and I have 15 entries in the "record" table where I have a newer "update_date" timestamp than 2020-06-17.
In the "recordversion" table I have one recent entry (update_date=2020-08-29), matching one of those 15 modified "recordid"s where the columns: "reference", "header", "data", "version", "previous_version_key" are blank/empty.
There is no other entry in the "recordversion" table where that's the case, could this be the problematic entry? The date could match my modification date of the problematic card. 

An help would be appreciated.

Matthias

**Comment by mt-mrx** [comment]
Hi,

I "fixed" my previous issue by deleting the specific record which had the empty values in the recordversion tables.

However today I managed to recreate the issue. It looks like if you only change the Notes field of a card the recordversion table entry is corrupted.

1. Create a new card, enter anything you like, add something for the username etc.
2. Save the card, results in new recordid
3. Edit the card and **only** change the "Notes" field, either edit previously entered Notes or add new text
4. Save the card
5. as a result the recordversion table has now an invalid entry for the newly created recordid
6. as long as you don't log out you can still modify the card
7. edit the card and modify any of the other entries, not the Notes field
8. save the card
9. as a result the recordversion table has again a valid entry

Not sure if I'm the only one who has this issue, but maybe this helps someone.

Matthias

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
