### ISSUE TITLE
Problem when try to login

### ISSUE THREAD

**Issue by RodrigoWebDev** [clipperz/password-manager#145]
I have an account and today I was not able to login and my brother too. I did not forget my password or username, both are correct, I think there is a problem with the server or something like this

![image](https://user-images.githubusercontent.com/30677819/163522568-628b1e3f-c1b8-43d3-a5dc-a3625bb10304.png)

**Comment by gcsolaroli** [comment]
We actually had an issue (disk full 😢) that has now been fixed. Sorry for the trouble.
