### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by RodrigoWebDev** [clipperz/password-manager#146]
I love clipperz, and I will love even more if it have a markdown support. I noticed that it already have a input for notes so I think this is a good place to add markdown text

![image](https://uploads.linear.app/11d1c384-f43c-4eef-9070-a839a63aff9a/ab333d74-9480-4e38-9bed-7e0375a237a1/fbc5344f-2a7e-4f58-a0b8-31c84c4a0971?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzExZDFjMzg0LWY0M2MtNGVlZi05MDcwLWE4MzlhNjNhZmY5YS9hYjMzM2Q3NC05NDgwLTRlMzgtOWJlZC03ZTAzNzVhMjM3YTEvZmJjNTM0NGYtMmE3ZS00ZjU4LWEwYjgtMzFjODRjNGEwOTcxIiwiaWF0IjoxNzExOTAwMDU3LCJleHAiOjMzMjgyNDYwMDU3fQ.Z_uWxej7HfhDyANqHsnuXrjZXhkHH9yIFqDJC4wSOH4)

**Comment by fsolaroli** [comment]
This feature has been added to the new (not yet released) epsilon version.
