### ISSUE TITLE
Community edition install on PHP 5.3.x??

### ISSUE THREAD

**Issue by Madsinzurich** [clipperz/password-manager#15]
Hi Clipperz and group,

I am getting a ton of those messages when creating the php objects
(POG). My guess is that this is because my php version is later than
the one Clipperz community is written for, and the split() function is
deprecated in 5.3.0.

I tried to exchange all the split() functions with explode() functions, but with no luck. I might not have done it right.. 

I just ask if anyone had found a way to install Clipperz community
version with a later version of php than 5.1 so i could avoid downgrading
(don't like to go backwards.. ;o)

Thanks for any input - even if it is: "NO! It's not possible..."

Sincerely

/Mads

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
