### ISSUE TITLE
create user "Registration error"

### ISSUE THREAD

**Issue by cisco722** [clipperz/password-manager#153]
Hi everyone, I'm asking for help with the local installation of clipperz password manager, I have an old instance installed and I wanted to update it on a new machine, I installed the whole problem is that when the user is created I get the "registration error" failed, but on the DB side via POD I see that the users are correctly added.

The version of PHP I'm using is "PHP Version 5.5.9-1ubuntu4.29" this is the apache error logo

[Mon Oct 23 08:22:18.382274 2023] [:error] [pid 1744] [client 192.168.38.53:57640] handshake, referer: http://192.168.38.222/
[Mon Oct 23 08:22:18.383255 2023] [:error] [pid 1744] [client 192.168.38.53:57640] credentialCheck, referer: http://192.168.38.222/
[Mon Oct 23 08:22:18.442177 2023] [:error] [pid 1744] [client 192.168.38.53:57640] result: {"result":{"error":"?"}}, referer: http:/ /192.168.38.222/
[Mon Oct 23 08:22:18.458345 2023] [:error] [pid 1744] [client 192.168.38.53:57640] handshake, referer: http://192.168.38.222/
[Mon Oct 23 08:22:18.494068 2023] [:error] [pid 1744] [client 192.168.38.53:57640] result: {"result":{"s":"112233445566778899aabbccddeeff001122334455667788 99aabbccddeeff00","B":"94dc82623974e2cc80fd7f660938781a002c4cefae426d96dbcccc3232ef1ef8" }}, referer: http://192.168.38.222/

I thank in advance anyone who can help me.

Francesco

**Comment by gcsolaroli** [comment]
Sorry we are not able to provide much support to the PHP backend.
With the new `/epsilon` version, we are fully sharing the new `scala` backend.
