### ISSUE TITLE
Impossible to build : Python error

### ISSUE THREAD

**Issue by ComputingFroggy** [clipperz/password-manager#157]
I've tried to build _clipperz_ on Ubuntu 22.04.
It looks like the builder is expecting _python2_, but it's deprecated. There's no _python_ command as expected by the builder.
And lastly, the builder expects that _python-git_ package will be installed ... but it's no longer available (on Ubuntu 20.04). 

It seems the builder should be updated to run _python3_.

**Comment by gcsolaroli** [comment]
We are no longer updating the `/delta` version, nor its build script.

We are working on the new `/epsilon` version that has been redone from scratch, and also the building process is completely different.
