### ISSUE TITLE
Which MySQL version is supported - it failed instalation on MySQL 8

### ISSUE THREAD

**Issue by mantonik** [clipperz/password-manager#170]
Hi. 
Which version of the MySQL is supported by this project?

I try to install it on MySQL 8 ( Oracle OCI service ) 
Table creation failed - I see engine is MyISAM, i think this engine is not available in this server. 
when I removed engine, it used default Innodb, it got throw check for tables, but then failed to insert data ( second step in instalation) 
when I see query - query don't have any values for required ID columns
When I add values to qeury it will insert query 

Sample of query which failed 

CHECKED 5 OBJECT(S). FOUND 3 ERROR(S):
---------------------------------------------------
Query failed: insert into `onetimepassword` (`userid`, `onetimepasswordstatusid`, `reference`, `key`, `key_checksum`, `data`, `version`, `creation_date`, `request_date`, `usage_date` ) values (
			'', 
			'', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'1997-12-15 23:50:26', 
			'1997-12-15 23:50:26', 
			'1997-12-15 23:50:26' )

Object onetimepassword failed essential tests

Query failed: insert into `record` (`userid`, `reference`, `data`, `version`, `creation_date`, `update_date`, `access_date` ) values (
			'', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'1997-12-15 23:50:26', 
			'Wed, 17 Apr 2024 13:29:26 +0000', 
			'Wed, 17 Apr 2024 13:29:26 +0000' )

Object record failed essential tests

Query failed: insert into `recordversion` (`recordid`, `reference`, `header`, `data`, `version`, `previous_version_key`, `previous_version_id`, `creation_date`, `update_date`, `access_date` ) values (
			'', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'Lorem Ipsum is simply dummy text of the printing and typesetting industry', 
			'12345678', 
			'1997-12-15 23:50:26', 
			'2024-04-17 13:29:26', 
			'2024-04-17 13:29:26' )

Object recordversion failed essential tests

**Comment by gcsolaroli** [comment]
Hello @mantonik, unfortunately we are no longer able to support the installation of the Community-Edition.
We are focused on developing the new /epsilon version (currently on the `develop` branch) that will feature a brand new "unified" backend (that is, the online version will be using the same code present in the public repository).
This will make it much easier to deploy the application in your own environment.
