### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by qoomon** [clipperz/password-manager#171]
Just wanna say thanks for this awesome password manager service.
I really appreciate your time and effort you put into this project.
Looking forward to the next [release](https://clipperz.is/versions/epsilon/)

![giphy](https://uploads.linear.app/11d1c384-f43c-4eef-9070-a839a63aff9a/0785696b-d7e3-415c-8562-d65827653243/0dde75fa-8a54-4399-9cd6-8a08b6ce9f01?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzExZDFjMzg0LWY0M2MtNGVlZi05MDcwLWE4MzlhNjNhZmY5YS8wNzg1Njk2Yi1kN2UzLTQxNWMtODU2Mi1kNjU4Mjc2NTMyNDMvMGRkZTc1ZmEtOGE1NC00Mzk5LTljZDYtOGEwOGI2Y2U5ZjAxIiwiaWF0IjoxNzE1MjY0MDc1LCJleHAiOjMzMjg1ODI0MDc1fQ.0mbM-3TYAF8jqgNVIUTkBYpBB4TqYlzQ-3Qe0A_YtrY)

**Comment by gcsolaroli** [comment]
Thanks! 🙏
