### ISSUE TITLE
Microsoft Edge reports https://clipperz.is/app as a "Dangerous" Site

### ISSUE THREAD

**Issue by petrsnm** [clipperz/password-manager#175]
![image](https://github.com/user-attachments/assets/6c6656c6-4ff7-4005-9407-b73a9816ee00)

**Comment by i-report-bugs** [comment]
Doesn't happen with me, even when i turned on all the privacy and security stuff all the way up in settings.

![image](https://github.com/user-attachments/assets/9d97cef7-79e9-4707-991c-ac5c6eede802)
