### ISSUE TITLE
Feature Request - Ability to insert in between items on cards.

### ISSUE THREAD

**Issue by gyoza** [clipperz/password-manager#21]
Since the cards do not automatically alphabetize and easy way to help manage a lot of info in one card would be to add the ability to insert lines between items when editing a card.

Also a spacer button would be nice too so that all the info doesnt look all jumbled

right now we've been using empty fields to act as spacers but obviously that is not the intended use. Thanks!

**Comment by gcsolaroli** [comment]
Field rearrangement has been available for a while, at least since `/delta` version.
Cleaning up some old neglected issues.
