### ISSUE TITLE
Question regarding past feature request - edit cards

### ISSUE THREAD

**Issue by gyoza** [clipperz/password-manager#22]
I am wondering if we can use jquery or on the browser itself greasemonkey+jquery to inject the button for adding a new line between every password line on clippers so we can stay a bit more organized in our cards  ( we like to keep history of our old passwords and the edit card layout makes this a little cumbersome) 

Would this break some type of chronological or password integrity that gets stored locally.

Please let me know.

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
