### ISSUE TITLE
Problem with Offline copy generation

### ISSUE THREAD

**Issue by Dosman** [clipperz/password-manager#23]
Hi  
I've got the Community Edition working ok, and it seems to work as well as the old sourceforge version; however when I try to generate an Offline copy of the database (where it generates a self contained html file that includes the encrypted db), it points a new browser window to a subdirectory /dump/ (which doesn't exist in the original build /target/php/ directory.    

There is a dump.php when run will dump the html code from the root directory, but adjusting the $htmlContent line in dump.php to point to the clipperz index.html just seems to lead to 'no web page found' errors.

I think where i've gone wrong is I've copied across the contents of /target/php/ to /var/www/clipperz and got it running, but perhaps  the directory structure is not quite right?  (I have to point the browser to /clipperz/beta obviously, but I don't want to mess any relative links in the code by moving the files in /beta/ up to the root directory).

Any tips?

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
