### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sechanbask** [clipperz/password-manager#59]
Hi,

I want to try clipperz on my server, I have followed guidelines :

apt-get install git-core bc php-services-json python-git

mkdir clipperz
cd clipperz

git clone git@github.com:clipperz/password-manager.git
cd password-manager
./scripts/build install --backends php python --frontends beta gamma

But it ends with AttributeError: 'NoneType' object has no attribute 'groups'

Can I have some help ?

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
