### ISSUE TITLE
where are direct logins gone?

### ISSUE THREAD

**Issue by g4ve** [clipperz/password-manager#71]
hi,
really enjoying the new clipperz layout!
but what about **direct logins**?
i found some of the already configured logins, some of those in the wrong card.
and i cannot find a way to create a new direct login.
is it my fault? it was a very useful feature...
thanks and cheers

**Comment by LeonardoGentile** [comment]
Exactly, I've been using the "add to clipperz" bookmarklet since the beginning of clipperz, the most convenient thing ever, and now its seems I can't use it anymore. I hope this will be implemented soon because copy-past each field and url it's not really an advancement

**Comment by jerefeltan** [comment]
Could some developer say something about this?
Is the plan to re-implement this feature?

**Comment by mbarulli** [comment]
Hi everyone,
unfortunately the way Clipperz direct logins work is compatible with an ever decreasing number of login forms. More reliable designs are possible, but they will leak information to the server (which website you are logging into, usage patterns, ...) and we are not going to make compromise on this aspect.

Therefore we are dismissing direct logins.
You can still use and delete existing ones, but will no longer able to create new ones.

I'm disappointed myself and we will keep looking for alternative solutions.

Cheers,
Marco

**Comment by LeonardoGentile** [comment]
@mbarulli thanks for your response :+1: 
Would you at least consider the possibility to re-introduce the "add to clipperz" functionality in conjunction with the bookmarklet? Even tough it won't create a direct login it's very very useful to pre-fill the form with (generally) user and password, then we can dismiss the link as the direct login is too problematic but pre-filling the form would be a valuable re-introduction (IMO).

**Comment by mbarulli** [comment]
It is something we may certainly consider.
You may have noticed that many things are under development at Clipperz and we need to carefully choose where to spend our limited resources.

Many thanks for your comprehension!

**Comment by steima** [comment]
Perhaps another option would be to develop a browser plugin which can talk to a Clipperz backend. This way auto-login would be much more integrated in the users browser UX and logins would be more reliable.

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
