### ISSUE TITLE
QR codes from passwords

### ISSUE THREAD

**Issue by ghost** [clipperz/password-manager#72]
Apart from the "reveal password" button, I think a button to generate a QR code from a password/username would be useful: when using an account on a mobile device and being logged in to clipperz on a PC, QR codes are a quick and easy way to copy a complicated password to a mobile device.
MIT-Licensed Javascript library for generating QR codes:
http://davidshimjs.github.io/qrcodejs/

**Comment by gcsolaroli** [comment]
Cleaning up some old neglected issues.
