### ISSUE TITLE
A problem with the lock in the offline copy

### ISSUE THREAD

**Issue by participante0** [clipperz/password-manager#89]
Steps to reproduce it:
1. Download the offline copy of the release 2015.10.02 (f2b85dd).
2. Lock the app.
3. Unlock it.
You will see the message `validating...` present always.

**Comment by gcsolaroli** [comment]
@participante0 thanks for the report; there is an exception thrown by the history API that we need to avoid/catch when in offline mode.

**Comment by participante0** [comment]
New release 2015.10.12 (f2b85dd).
It is fixed in Google Chrome but not in Firefox.

**Comment by participante0** [comment]
New release 2015.10.27 (8608fb4).
Now it is fixed in both web browser. Thanks. I will close this issue.

**Comment by gcsolaroli** [comment]
Thanks for the feedback.
