### ISSUE TITLE
Login failed on offline copy.

### ISSUE THREAD

**Issue by isabelacristinaterra** [clipperz/password-manager#92]
Hello, did I install the beta and delta versions only that both had the same problem.
The new user account functions normally, but when you log gives error "Login failed".

Apache error:
[Fri Nov 13 10: 47: 23.219586 2015] [: error] [pid 1772] [client 192.168.52.25:64614] handshake, referer: http://192.168.3.82/clipperz/beta/index.html
[Fri Nov 13 10: 47: 23.220374 2015] [: error] [pid 1772] [client 192.168.52.25:64614] credentialCheck, referer: http://192.168.3.82/clipperz/beta/index.html
[Fri Nov 13 10: 47: 23.353236 2015] [: error] [pid 1772] [client 192.168.52.25:64614] result: {"result": {"error": ""}}, referer: http: / /192.168.3.82/clipperz/beta/index.html

Someone help me?
Thank you!

**Comment by ManuCart** [comment]
Same for me.
Only on Google Chrome but with IE after login impossible to view select card
