### ISSUE TITLE
How to change the port 8888

### ISSUE THREAD

**Issue by ManuCart** [clipperz/password-manager#93]
Hello, I need to change the port 8888 because this one is allready in used by btsync.
How to do this?

**Comment by gcsolaroli** [comment]
Hello @ManuCart,

the port where the development proxy runs is defined [here](https://github.com/clipperz/password-manager/blob/master/scripts/proxy/main.py#L127).

Hope this helps.

**Comment by ManuCart** [comment]
Ok, thanks for your help
